spring.application.name=Restaurant-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=5Rwandan
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.jwt.secret=eTH+ZnxtspezkV4qMcvmL97NrsvTQ66t4Jlg+I2kb+MAV4txYNrxQwq1pOql596HrWvms589AVJ+EHpa4iWyYw==
app.jwt.expiration-ms=86400000

#  CORS (tighten origins before going to production) 
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

#  Mail (for password reset / receipts) 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leopordbonfils@gmail.com
spring.mail.password=sihazjarybknauyi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#  Logging 
logging.level.com.restaurant=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG